# whenever new issue is openend, this workflow will create comment on it

name: Create a comment on the new issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event)}}' | jq
        shell: bash

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: create comment with
        run: |
          gh api -X POST \
           https://api.github.com/repo/$(ORGANIZATION)/$REPOSITORY/issues/${ISSUE_NUMBER}/comments \
           -f body='
           Comment but from the API call not from action
           '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organisation.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
